apiVersion: v1
kind: Service
metadata:
  name: {{ include "araldo.fullname" . }}
  labels:
    {{- include "araldo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "araldo.selector" (dict "root" . "component" "server") | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
