// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// zones_generate writes zones_gen.go: the IANA time zones brands can pick,
// read from the Go toolchain's own tz database (the same data the binary
// embeds with time/tzdata). Run with `go generate ./internal/web`.
package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Regions people pick from; everything else (Etc/, US/, legacy aliases)
// is left out of the list but still accepted if typed through the API.
var regions = map[string]bool{
	"Africa": true, "America": true, "Antarctica": true, "Asia": true, "Atlantic": true,
	"Australia": true, "Europe": true, "Indian": true, "Pacific": true,
}

func main() {
	zr, err := zip.OpenReader(filepath.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip"))
	if err != nil {
		log.Fatal(err)
	}
	defer zr.Close()
	var zones []string
	for _, f := range zr.File {
		region, _, ok := strings.Cut(f.Name, "/")
		if ok && regions[region] {
			zones = append(zones, f.Name)
		}
	}
	sort.Strings(zones)
	var buf bytes.Buffer
	buf.WriteString("// Code generated by zones_generate.go; DO NOT EDIT.\n\npackage web\n\n")
	buf.WriteString("// timeZones are the IANA zones offered for brands, by region.\nvar timeZones = []string{\n")
	for _, z := range zones {
		fmt.Fprintf(&buf, "\t%q,\n", z)
	}
	buf.WriteString("}\n")
	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("zones_gen.go", src, 0o644); err != nil { //nolint:gosec // a source file
		log.Fatal(err)
	}
}
